# Generated by Django 4.2.5 on 2023-10-02 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_cat_toys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finch',
            name='toys',
        ),
    ]
